name: Tag And Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
        
      - name: Component detection
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.1

      - name: Get run-id for build workflow for the commit sha
        id: get_run_id
        continue-on-error: true
        shell: pwsh
        run: |
          $workflowName = "PR"
          $runs = gh run list -w "$workflowName" -c $env:GITHUB_SHA --json databaseId,updatedAt --jq 'sort_by(.updatedAt) | .[] | .databaseId' --repo ${{ github.repository }}
          if ($runs.Count -eq 0) {
              Write-Error "No workflow runs found for commit SHA $env:GITHUB_SHA"
              exit 1
          }
          elseif ($runs.Count -gt 1) {
              Write-Error "Multiple workflow runs found for commit SHA $env:GITHUB_SHA"
              exit 1
          }
          
          else {
              Write-Output "Got run ID: $runs"
              "run_id=$runs" >> $env:GITHUB_OUTPUT
          }

      - name: Fetch artifacts from build workflow
        uses: actions/download-artifact@v4
        if: steps.get_run_id.outcome == 'success'
        id: download_artifacts
        with:
          run-id: ${{ steps.get_run_id.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: PrometheusWindowsHardwareExporter-Artifacts
          path: artifacts/

      - name: Build and package
        shell: pwsh
        if: steps.get_run_id.outcome != 'success' || steps.download_artifacts.outcome != 'success'
        run: |
          .\Scripts\ci_build.ps1 -publishDir $(Join-Path $env:GITHUB_WORKSPACE "publish") `
            -artifactsDir $(Join-Path $env:GITHUB_WORKSPACE "artifacts") `
            -version "${{ github.ref_name }}" `
            -pack $true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            artifacts/PrometheusWindowsHardwareExporter.msi
            artifacts/PrometheusWindowsHardwareExporter-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}